## Put comments here that give an overall description of what your
## functions do
##
##  Taking the inverse of a matrix is typically a fast operation. 
##  However, for a very large Matrices, it may take too long to compute the inverse, 
##  especially if it has to be computed repeatedly. 
##  If the contents of a matrix are not changing, 
##  it may make sense to cache the inverse of the matrix, 
##  so that when we need it again, it can be looked up in the cache rather than recomputed.
##
##  This is accomplihed by the makeCacheMatrix and cachSolve functions
##  makeCacheMatrix contains following cached data and functions:
##
##	Cached Data: matrix and its inverse
##
##	functions (methods):
##		set : sets the cached matrix
##		get : gets the cached matrix
##		setinv: sets the cached inverse
##		getinv: gets the cached inverse
##
##	retunrs list of the above functions.
##


## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {

        inv_x <- NULL
        set <- function(x) {
                x <<- x
                inv_x <<- NULL
        }
        get <- function() x
        setinv <- function(inverse) inv_x <<- inverse
        getinv <- function() inv_x
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## Write a short comment describing this function
##
## cacheSolve funtion  calculates the inverse by calling 
## the functions that were generated by makeCacheMatrix and solve function.
## if cache inverse (by getinv function) is not computed previosly ie: (if inverse == NULL), 
## then it reads the cache matrix by using makeCacheMatrix.get function and
## computes the inverse (by normal solve function) and sets the cache inverse (by using setinv function).
## future reads will only read the cache inverse it does not need to recompute the inverse.
##

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        
        inv_x <- x$getinv()
        if(!is.null(inv_x)) {
                message("getting cached data")
                return(inv_x)
        }
        data <- x$get()
        inv_x <- solve(data, ...)
        x$setinv(inv_x)
        inv_x        
}
